In [41]:
import pandas as pd

In [42]:
df=pd.read_csv("twitter_training.csv",names=["id","about","target","comment"])
df.head()

,id,about,target,comment
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [43]:
df["target"].value_counts()

target
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       74682 non-null  int64
 1   about    74682 non-null  str
 2   target   74682 non-null  str
 3   comment  73996 non-null  str
dtypes: int64(1), str(3)
memory usage: 11.4 MB

In [45]:
df=df[df["comment"].notna()]

In [46]:
df.info()

<class 'pandas.DataFrame'>
Index: 73996 entries, 0 to 74681
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       73996 non-null  int64
 1   about    73996 non-null  str
 2   target   73996 non-null  str
 3   comment  73996 non-null  str
dtypes: int64(1), str(3)
memory usage: 12.0 MB

In [47]:
df=df[["target","comment"]]
df.sample(10)

           target                                            comment
38546     Neutral  OB, The Pain Zone powered by The Nuclear Arcad...
61118    Positive                                         Thank fuck
35704     Neutral  Windows Windows Update doesn ’ t just automati...
50252    Negative                                   Fifa is dog shit
28678    Positive  2011 I had in total 5 wins in my Apex Legends ...
40612    Positive  2016 was such a good year for games. THE DOOM....
60958  Irrelevant  And The first one looks like the shit you only...
53810    Positive  I already own the game, but it had the best zo...
43985     Neutral  ..... Never want to miss every update?. Follow...
39119    Positive  One of my favorite makers makes @PlayHearthsto...

In [48]:
df=df.drop_duplicates()

In [49]:
df=df[(df["target"]=="Positive") | (df["target"]=="Negative") | (df["target"]=="Neutral")]

In [50]:
df["target"].value_counts()

target
Negative    21237
Positive    19138
Neutral     17110
Name: count, dtype: int64

In [51]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [52]:
tokenizer=Tokenizer(oov_token="Nothing")

In [53]:
tokenizer.fit_on_texts(df["comment"])

In [54]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'it': 11,
 'this': 12,
 'on': 13,
 'my': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'be': 21,
 'me': 22,
 'just': 23,
 'but': 24,
 'have': 25,
 'are': 26,
 'not': 27,
 'all': 28,
 'was': 29,
 'at': 30,
 'like': 31,
 '2': 32,
 'out': 33,
 'from': 34,
 'your': 35,
 'now': 36,
 'get': 37,
 'pic': 38,
 'twitter': 39,
 'as': 40,
 't': 41,
 'we': 42,
 'play': 43,
 'they': 44,
 'johnson': 45,
 'one': 46,
 'can': 47,
 'if': 48,
 'new': 49,
 'good': 50,
 'no': 51,
 'about': 52,
 'an': 53,
 'really': 54,
 'will': 55,
 'when': 56,
 'has': 57,
 'up': 58,
 'more': 59,
 "i'm": 60,
 'what': 61,
 'love': 62,
 'do': 63,
 '3': 64,
 'or': 65,
 'why': 66,
 'how': 67,
 'unk': 68,
 'by': 69,
 'time': 70,
 'co': 71,
 'shit': 72,
 'some': 73,
 "it's": 74,
 'been': 75,
 'amazon': 76,
 'still': 77,
 '’': 78,
 'https': 79,
 'people': 80,
 'facebook': 81,
 'games': 82,
 'best': 83,
 'microsoft': 84,
 'verizon': 85,
 'playing': 86,
 'got': 87,
 '1': 88,
 'see': 89,
 'xbox': 90,
 'even': 91,
 'great': 92,
 'dead': 93,
 'because': 94,
 'google': 95,
 'rhandlerr': 96,
 'go': 97,
 'fuck': 98,
 'please': 99,
 'fucking': 100,
 'red': 101,
 'back': 102,
 'had': 103,
 'us': 104,
 'home': 105,
 '5': 106,
 'only': 107,
 'much': 108,
 'who': 109,
 'going': 110,
 'after': 111,
 'am': 112,
 'nvidia': 113,
 'their': 114,
 's': 115,
 'its': 116,
 'fix': 117,
 'there': 118,
 "can't": 119,
 'borderlands': 120,
 'make': 121,
 'over': 122,
 'know': 123,
 'fifa': 124,
 'our': 125,
 'again': 126,
 'would': 127,
 "don't": 128,
 'tv': 129,
 'than': 130,
 'fun': 131,
 'them': 132,
 'day': 133,
 'these': 134,
 '4': 135,
 '2020': 136,
 'very': 137,
 'eamaddennfl': 138,
 '…': 139,
 'first': 140,
 'also': 141,
 'today': 142,
 'bad': 143,
 'here': 144,
 'ever': 145,
 'want': 146,
 'nba2k': 147,
 'rainbow6game': 148,
 'then': 149,
 'pubg': 150,
 'every': 151,
 'he': 152,
 'wait': 153,
 'redemption': 154,
 'never': 155,
 'thank': 156,
 'x': 157,
 'ps5': 158,
 'call': 159,
 'world': 160,
 'year': 161,
 'series': 162,
 '10': 163,
 'depot': 164,
 'twitch': 165,
 'news': 166,
 'gta': 167,
 'video': 168,
 'right': 169,
 'getting': 170,
 'too': 171,
 'work': 172,
 'off': 173,
 "i've": 174,
 'think': 175,
 'thanks': 176,
 'played': 177,
 'amazing': 178,
 'last': 179,
 'legends': 180,
 'v': 181,
 'watch': 182,
 'any': 183,
 'league': 184,
 'most': 185,
 'well': 186,
 'help': 187,
 'guys': 188,
 'u': 189,
 'being': 190,
 'into': 191,
 'black': 192,
 'ghostrecon': 193,
 'i’m': 194,
 'down': 195,
 'years': 196,
 'youtu': 197,
 'looks': 198,
 'happy': 199,
 'did': 200,
 'actually': 201,
 'damn': 202,
 'overwatch': 203,
 'warcraft': 204,
 'man': 205,
 'another': 206,
 'youtube': 207,
 'creed': 208,
 'stop': 209,
 'team': 210,
 'next': 211,
 'buy': 212,
 'made': 213,
 'should': 214,
 'live': 215,
 'need': 216,
 'battlefield': 217,
 'everyone': 218,
 'say': 219,
 'duty': 220,
 'always': 221,
 'finally': 222,
 'via': 223,
 'since': 224,
 'could': 225,
 'look': 226,
 'big': 227,
 'update': 228,
 'm': 229,
 'which': 230,
 'hearthstone': 231,
 'players': 232,
 'csgo': 233,
 'way': 234,
 'many': 235,
 'better': 236,
 'free': 237,
 'something': 238,
 'excited': 239,
 'it’s': 240,
 'already': 241,
 'online': 242,
 'his': 243,
 'were': 244,
 'money': 245,
 'win': 246,
 'other': 247,
 'fortnite': 248,
 'store': 249,
 'nice': 250,
 'thing': 251,
 'come': 252,
 'playstation': 253,
 '20': 254,
 'hate': 255,
 '6': 256,
 'take': 257,
 'playapex': 258,
 'while': 259,
 'days': 260,
 'having': 261,
 'support': 262,
 'give': 263,
 'war': 264,
 'two': 265,
 'before': 266,
 'wtf': 267,
 'wow': 268,
 'stream': 269,
 'bit': 270,
 'awesome': 271,
 'where': 272,
 'ass': 273,
 'keep': 274,
 'gonna': 275,
 'trying': 276,
 'servers': 277,
 'ly': 278,
 'pc': 279,
 'lol': 280,
 'done': 281,
 'ubisoft': 282,
 'does': 283,
 'same': 284,
 'life': 285,
 'looking': 286,
 'her': 287,
 'long': 288,
 'baby': 289,
 'everything': 290,
 'check': 291,
 'someone': 292,
 'old': 293,
 'pretty': 294,
 'through': 295,
 'dota': 296,
 'oh': 297,
 'lot': 298,
 'him': 299,
 'cool': 300,
 'feel': 301,
 'use': 302,
 'doing': 303,
 'super': 304,
 'both': 305,
 'hey': 306,
 'top': 307,
 'nothing': 308,
 'im': 309,
 'card': 310,
 'company': 311,
 'hell': 312,
 'real': 313,
 'uk': 314,
 'account': 315,
 'night': 316,
 'things': 317,
 'mobile': 318,
 'making': 319,
 'such': 320,
 'cyberpunk': 321,
 'makes': 322,
 'ops': 323,
 'favorite': 324,
 'start': 325,
 'problem': 326,
 'anyone': 327,
 '2077': 328,
 'working': 329,
 'little': 330,
 'until': 331,
 '7': 332,
 'powder': 333,
 'cold': 334,
 'worst': 335,
 'those': 336,
 'try': 337,
 'literally': 338,
 'phone': 339,
 'won': 340,
 'god': 341,
 'service': 342,
 'hours': 343,
 'gaming': 344,
 '100': 345,
 'probably': 346,
 "that's": 347,
 'ea': 348,
 'let': 349,
 'week': 350,
 'player': 351,
 'almost': 352,
 'story': 353,
 'hard': 354,
 'said': 355,
 'yet': 356,
 'few': 357,
 'season': 358,
 'against': 359,
 'can’t': 360,
 'hope': 361,
 'stupid': 362,
 'times': 363,
 'show': 364,
 'whole': 365,
 'miss': 366,
 'app': 367,
 "doesn't": 368,
 'sure': 369,
 'around': 370,
 'apex': 371,
 'find': 372,
 'pay': 373,
 'chance': 374,
 '19': 375,
 'internet': 376,
 'anything': 377,
 '2k': 378,
 'far': 379,
 'ranked': 380,
 'console': 381,
 'lost': 382,
 'release': 383,
 'cant': 384,
 'end': 385,
 'open': 386,
 '21': 387,
 'part': 388,
 'own': 389,
 'don’t': 390,
 'callofduty': 391,
 'says': 392,
 'friends': 393,
 'stuff': 394,
 'maybe': 395,
 'coming': 396,
 'ban': 397,
 'using': 398,
 'crazy': 399,
 'mode': 400,
 'business': 401,
 'ps4': 402,
 'without': 403,
 'beautiful': 404,
 'full': 405,
 'minutes': 406,
 'absolutely': 407,
 "didn't": 408,
 'guy': 409,
 'trash': 410,
 'thought': 411,
 'order': 412,
 'put': 413,
 'tell': 414,
 'dont': 415,
 'cs': 416,
 'tonight': 417,
 'org': 418,
 'italy': 419,
 'enough': 420,
 "assassin's": 421,
 'enjoy': 422,
 'e': 423,
 'broken': 424,
 'w': 425,
 'tried': 426,
 'month': 427,
 'madden': 428,
 'vaccine': 429,
 'tt': 430,
 '0': 431,
 'gameplay': 432,
 'gets': 433,
 'd': 434,
 'interesting': 435,
 'assassins': 436,
 'used': 437,
 'went': 438,
 'epic': 439,
 'care': 440,
 'covid': 441,
 'screen': 442,
 'wrong': 443,
 'run': 444,
 '30': 445,
 'point': 446,
 'though': 447,
 'bought': 448,
 'change': 449,
 '12': 450,
 'sad': 451,
 'kill': 452,
 'y’all': 453,
 'perfect': 454,
 'reason': 455,
 "won't": 456,
 'hit': 457,
 'banned': 458,
 'soon': 459,
 'feels': 460,
 '15': 461,
 'cod': 462,
 'selling': 463,
 'p': 464,
 'watching': 465,
 'may': 466,
 'worth': 467,
 'cause': 468,
 '9': 469,
 'skin': 470,
 'net': 471,
 'problems': 472,
 'due': 473,
 "y'all": 474,
 'launch': 475,
 'system': 476,
 'data': 477,
 'away': 478,
 'price': 479,
 'forward': 480,
 'seems': 481,
 'bro': 482,
 'grand': 483,
 'post': 484,
 'myself': 485,
 'i’ve': 486,
 'definitely': 487,
 "you're": 488,
 '8': 489,
 'huge': 490,
 "i'll": 491,
 'high': 492,
 'based': 493,
 'able': 494,
 'playhearthstone': 495,
 'dota2': 496,
 'might': 497,
 'content': 498,
 'read': 499,
 'ago': 500,
 'months': 501,
 'exciting': 502,
 'tomorrow': 503,
 'patch': 504,
 'pro': 505,
 'homedepot': 506,
 'comes': 507,
 'instead': 508,
 'idea': 509,
 'buying': 510,
 'talc': 511,
 'finished': 512,
 'server': 513,
 'job': 514,
 'sorry': 515,
 'experience': 516,
 'terrible': 517,
 'needs': 518,
 'graphics': 519,
 'dlvr': 520,
 'power': 521,
 'match': 522,
 'sucks': 523,
 'half': 524,
 'cards': 525,
 'odyssey': 526,
 'morning': 527,
 'place': 528,
 'windows': 529,
 'else': 530,
 'community': 531,
 'ift': 532,
 'myteam': 533,
 'second': 534,
 'latest': 535,
 'during': 536,
 'character': 537,
 'pre': 538,
 'started': 539,
 'wanted': 540,
 'saying': 541,
 'share': 542,
 'c': 543,
 'seen': 544,
 'music': 545,
 'she': 546,
 'came': 547,
 'event': 548,
 'yes': 549,
 'completely': 550,
 'streaming': 551,
 'once': 552,
 'wanna': 553,
 'must': 554,
 'found': 555,
 'issues': 556,
 'took': 557,
 'ok': 558,
 'single': 559,
 'rewards': 560,
 '”': 561,
 'name': 562,
 'die': 563,
 'trailer': 564,
 'weekend': 565,
 'anymore': 566,
 'different': 567,
 'mean': 568,
 'honestly': 569,
 'breakpoint': 570,
 'worse': 571,
 'hour': 572,
 'seriously': 573,
 'level': 574,
 'n2k': 575,
 'yo': 576,
 'r': 577,
 'friend': 578,
 'luck': 579,
 'error': 580,
 'gold': 581,
 'hi': 582,
 'running': 583,
 'remember': 584,
 'list': 585,
 'link': 586,
 'guess': 587,
 'rtx': 588,
 'easports': 589,
 'issue': 590,
 'annoying': 591,
 'points': 592,
 'holy': 593,
 'earned': 594,
 'ghost': 595,
 'apple': 596,
 'ready': 597,
 'achievement': 598,
 '•': 599,
 'less': 600,
 'later': 601,
 'either': 602,
 'blizzard': 603,
 'fortnitegame': 604,
 'face': 605,
 'tech': 606,
 'page': 607,
 'yall': 608,
 'deal': 609,
 'entire': 610,
 'customer': 611,
 'products': 612,
 'ubisoftsupport': 613,
 'called': 614,
 'switch': 615,
 'fact': 616,
 'set': 617,
 're': 618,
 'proud': 619,
 'shot': 620,
 'fan': 621,
 'major': 622,
 'three': 623,
 'warzone': 624,
 'kind': 625,
 'left': 626,
 'cannot': 627,
 'seeing': 628,
 'kinda': 629,
 'break': 630,
 'person': 631,
 'talk': 632,
 'starting': 633,
 'saw': 634,
 'understand': 635,
 'least': 636,
 'review': 637,
 'taking': 638,
 'apps': 639,
 'lmao': 640,
 'pass': 641,
 'death': 642,
 'move': 643,
 'j': 644,
 'ronnie2k': 645,
 'early': 646,
 'hear': 647,
 'incredible': 648,
 'bring': 649,
 'omg': 650,
 'india': 651,
 'past': 652,
 'sick': 653,
 'join': 654,
 'house': 655,
 'easy': 656,
 'wikipedia': 657,
 'loved': 658,
 'leagueoflegends': 659,
 'funny': 660,
 'glad': 661,
 'action': 662,
 'waiting': 663,
 'global': 664,
 'small': 665,
 'sounds': 666,
 'companies': 667,
 'follow': 668,
 'fans': 669,
 'killed': 670,
 'b': 671,
 'battle': 672,
 'final': 673,
 'gift': 674,
 'number': 675,
 'class': 676,
 'weeks': 677,
 'tired': 678,
 'each': 679,
 'birthday': 680,
 'believe': 681,
 'gen': 682,
 'quite': 683,
 'mad': 684,
 'happened': 685,
 'delayed': 686,
 '3080': 687,
 'cancer': 688,
 'goes': 689,
 'article': 690,
 'beluba': 691,
 'fantastic': 692,
 'market': 693,
 'family': 694,
 'add': 695,
 'sometimes': 696,
 'franchise': 697,
 'turn': 698,
 "haven't": 699,
 'y': 700,
 'together': 701,
 'line': 702,
 'heart': 703,
 'updates': 704,
 'o': 705,
 'connection': 706,
 'leave': 707,
 'social': 708,
 'n': 709,
 'history': 710,
 'smh': 711,
 'main': 712,
 'kills': 713,
 'modern': 714,
 'totally': 715,
 'code': 716,
 'version': 717,
 "what's": 718,
 'hello': 719,
 'fps': 720,
 'hot': 721,
 'moments': 722,
 'design': 723,
 'bullshit': 724,
 'trump': 725,
 'decided': 726,
 'bc': 727,
 'yeah': 728,
 'close': 729,
 'f': 730,
 'ur': 731,
 'don': 732,
 'yesterday': 733,
 'including': 734,
 'videos': 735,
 'email': 736,
 'characters': 737,
 'mind': 738,
 'movie': 739,
 'speed': 740,
 'gotta': 741,
 'garbage': 742,
 "let's": 743,
 'white': 744,
 'complete': 745,
 'services': 746,
 'suck': 747,
 '–': 748,
 "we're": 749,
 've': 750,
 "there's": 751,
 'original': 752,
 "they're": 753,
 'truly': 754,
 'teams': 755,
 'retweet': 756,
 'canada': 757,
 'thinking': 758,
 'access': 759,
 'edition': 760,
 'spend': 761,
 'released': 762,
 'between': 763,
 'en': 764,
 'available': 765,
 'talking': 766,
 'sound': 767,
 'sony': 768,
 'gone': 769,
 'especially': 770,
 'test': 771,
 'wish': 772,
 'current': 773,
 'beta': 774,
 'keeps': 775,
 '11': 776,
 'that’s': 777,
 'gpu': 778,
 'late': 779,
 'told': 780,
 'sold': 781,
 'nba': 782,
 'ridiculous': 783,
 '“': 784,
 'playoverwatch': 785,
 'crap': 786,
 'daily': 787,
 'million': 788,
 'technology': 789,
 'spent': 790,
 'biggest': 791,
 'moment': 792,
 'absolute': 793,
 'giving': 794,
 'warfare': 795,
 'search': 796,
 'true': 797,
 'instagram': 798,
 'stay': 799,
 'massive': 800,
 'health': 801,
 'within': 802,
 'book': 803,
 'map': 804,
 'under': 805,
 'longer': 806,
 'performance': 807,
 'low': 808,
 'sell': 809,
 'fast': 810,
 'welcome': 811,
 'lose': 812,
 'car': 813,
 'drop': 814,
 'star': 815,
 'item': 816,
 '24': 817,
 'pls': 818,
 'currently': 819,
 'works': 820,
 'controller': 821,
 'customers': 822,
 'nfl': 823,
 'mut': 824,
 'bitch': 825,
 'report': 826,
 'hyped': 827,
 '99': 828,
 'stock': 829,
 'toxic': 830,
 'fire': 831,
 'okay': 832,
 'geforce': 833,
 'greatest': 834,
 'stuck': 835,
 'clips': 836,
 'ordered': 837,
 'unit': 838,
 'shows': 839,
 'feeling': 840,
 'city': 841,
 '50': 842,
 'special': 843,
 'behind': 844,
 'date': 845,
 'means': 846,
 'men': 847,
 'insane': 848,
 'killing': 849,
 'coronavirus': 850,
 'cute': 851,
 'plays': 852,
 'eahelp': 853,
 'side': 854,
 'plus': 855,
 'congratulations': 856,
 'media': 857,
 'activision': 858,
 'prime': 859,
 'tweet': 860,
 'hero': 861,
 'bugs': 862,
 'stopped': 863,
 'campaign': 864,
 'official': 865,
 'digital': 866,
 'ai': 867,
 'valhalla': 868,
 'enjoyed': 869,
 'save': 870,
 'alone': 871,
 'tho': 872,
 'worked': 873,
 'trust': 874,
 'box': 875,
 'iphone': 876,
 'rockstargames': 877,
 'future': 878,
 'wants': 879,
 'trial': 880,
 'dlc': 881,
 'dude': 882,
 'website': 883,
 'happens': 884,
 'bug': 885,
 'girl': 886,
 'changes': 887,
 'received': 888,
 'cyberpunkgame': 889,
 'become': 890,
 'losing': 891,
 'joke': 892,
 'dear': 893,
 'computer': 894,
 'product': 895,
 'seem': 896,
 'imagine': 897,
 'sales': 898,
 'g': 899,
 'control': 900,
 'slow': 901,
 '25': 902,
 'wins': 903,
 'platform': 904,
 'dark': 905,
 'drive': 906,
 'takes': 907,
 'information': 908,
 'powerful': 909,
 'head': 910,
 'download': 911,
 'simply': 912,
 '14': 913,
 'pick': 914,
 'network': 915,
 'rt': 916,
 'racist': 917,
 'loving': 918,
 'safe': 919,
 'somehow': 920,
 "isn't": 921,
 'quality': 922,
 'word': 923,
 'recon': 924,
 'heard': 925,
 'continue': 926,
 'channel': 927,
 'crashing': 928,
 'yourself': 929,
 'boring': 930,
 'fight': 931,
 'broke': 932,
 'forever': 933,
 'log': 934,
 'dog': 935,
 'l': 936,
 'kids': 937,
 'hold': 938,
 'cuz': 939,
 'stores': 940,
 '60': 941,
 'fake': 942,
 'summoners': 943,
 'felt': 944,
 'boy': 945,
 'appreciate': 946,
 'created': 947,
 'disappointed': 948,
 'users': 949,
 '000': 950,
 'gamer': 951,
 'classic': 952,
 'random': 953,
 'articles': 954,
 'siege': 955,
 'important': 956,
 'rest': 957,
 'sense': 958,
 'buff': 959,
 'shitty': 960,
 'possible': 961,
 "i'd": 962,
 'shut': 963,
 'dying': 964,
 'skins': 965,
 'developers': 966,
 'finish': 967,
 'quit': 968,
 'mask': 969,
 'forgot': 970,
 'wild': 971,
 'sale': 972,
 'missing': 973,
 'esports': 974,
 'row': 975,
 'enjoying': 976,
 'art': 977,
 'brand': 978,
 'paid': 979,
 'twice': 980,
 'gave': 981,
 'matter': 982,
 'sea': 983,
 'auto': 984,
 'valve': 985,
 'others': 986,
 'shooting': 987,
 'learn': 988,
 'plan': 989,
 'golden': 990,
 'wonder': 991,
 'lie': 992,
 'amd': 993,
 'edge': 994,
 'group': 995,
 'died': 996,
 'tch': 997,
 'decision': 998,
 'listen': 999,
 'showing': 1000,
 ...}

In [55]:
tokenizer.word_counts

OrderedDict([('im', 548),
             ('getting', 1047),
             ('on', 9737),
             ('borderlands', 1413),
             ('and', 21551),
             ('i', 24308),
             ('will', 2675),
             ('murder', 68),
             ('you', 9291),
             ('all', 4491),
             ('am', 1516),
             ('coming', 403),
             ('to', 23272),
             ('the', 35286),
             ('borders', 11),
             ('kill', 348),
             ('2', 3709),
             ('me', 5514),
             ('into', 947),
             ('can', 2891),
             ('so', 6395),
             ('spent', 179),
             ('a', 19027),
             ('few', 467),
             ('hours', 481),
             ('making', 527),
             ('something', 752),
             ('for', 12481),
             ('fun', 1329),
             ('if', 2855),
             ("don't", 1337),
             ('know', 1391),
             ('huge', 310),
             ('fan', 228),
             ('maya', 22),
             ('is', 14272),
             ('one', 2917),
             ('of', 15261),
             ('my', 9731),
             ('favorite', 517),
             ('characters', 192),
             ('decided', 194),
             ('make', 1399),
             ('myself', 313),
             ('wallpaper', 14),
             ('pc', 624),
             ('here', 1236),
             ('original', 188),
             ('image', 54),
             ('versus', 13),
             ('creation', 6),
             ('made', 847),
             ('enjoy', 376),
             ('pic', 3316),
             ('twitter', 3167),
             ('com', 7744),
             ('mlsi5wf9jg', 4),
             ('couple', 132),
             ('doing', 561),
             ('that', 7976),
             ("i'm", 2532),
             ("here's", 108),
             ('picture', 83),
             ('compared', 63),
             ('have', 5087),
             ('rhandlerr', 1718),
             ('2010', 60),
             ('was', 4364),
             ('rock', 69),
             ('hard', 472),
             ('la', 71),
             ('varlope', 4),
             ('rare', 33),
             ('powerful', 147),
             ('handsome', 69),
             ('jackpot', 9),
             ('3', 2470),
             ('xbox', 1778),
             ('dlvr', 291),
             ('it', 11782),
             ('rmtrgf', 6),
             ('dfr', 7),
             ('vita', 12),
             ('but', 5203),
             ('1', 1832),
             ('live', 832),
             ('music', 274),
             ('sega', 26),
             ('from', 3549),
             ('e', 376),
             ('like', 3846),
             ('london', 21),
             ('de', 99),
             ('2011', 45),
             ('first', 1270),
             ('session', 73),
             ('in', 12699),
             ('long', 594),
             ('time', 2240),
             ('where', 640),
             ('actually', 900),
             ('had', 1608),
             ('really', 2681),
             ('satisfying', 48),
             ('combat', 59),
             ('experience', 294),
             ('got', 1838),
             ('some', 2187),
             ('good', 2816),
             ('kills', 199),
             ('this', 11742),
             ('fighting', 59),
             ('enjoyed', 159),
             ('rather', 123),
             ('real', 539),
             ('nice', 715),
             ('wait', 1145),
             ('hot', 196),
             ('row', 136),
             ('bad', 1237),
             ('did', 903),
             ('biggest', 179),
             ('dissappoinment', 4),
             ('life', 605),
             ('came', 273),
             ('out', 3560),
             ('year', 1090),
             ('ago', 301),
             ('fuck', 1692),
             ('disappointment', 62),
             ('male', 17),
             ('hanging', 62),
             ('back', 1613),
             ('last', 1010),
             ('we', 3033),
             ('finished', 296),
             ('finally', 798),
             ('yas', 10),
             ('thank', 1133),
             ('everyone', 822),
             ('try', 492),
             ('stream', 644),
             ('tomorrow', 300),
             ('not', 4638),
             ('might', 302),
             ('irl', 44),
             ('streams', 57),
             ('while', 663),
             ('awayu', 4),
             ('shall', 40),
             ('see', 1794),
             ('much', 1547),
             ('raids', 29),
             ('mompou', 6),
             ('mumpow', 6),
             ('megamagwitch', 4),
             ('kfdmitch', 3),
             ('find', 439),
             ('yes', 271),
             ("i'll", 310),
             ('maybe', 404),
             ("we'll", 56),
             ('thanks', 1032),
             ('up', 2552),
             ('get', 3406),
             ('haircut', 8),
             ("wasn't", 82),
             ('would', 1340),
             ('still', 2121),
             ('be', 5657),
             ('hawaii', 3),
             ('megamagwife', 1),
             ('fendmitch', 1),
             ('update', 775),
             ('guys', 968),
             ('even', 1771),
             ('go', 1701),
             ('hope', 464),
             ('10', 1087),
             ('never', 1138),
             ('both', 554),
             ('or', 2439),
             ('4', 1302),
             ('hey', 554),
             ('use', 563),
             ('how', 2393),
             ('many', 762),
             ('their', 1481),
             ('man', 886),
             ('gearbox', 30),
             ('needs', 292),
             ('fix', 1447),
             ('dissapointing', 3),
             ('drops', 94),
             ('new', 2849),
             ('dlc', 156),
             ('cant', 414),
             ('fine', 132),
             ('farm', 24),
             ('bosses', 15),
             ('mayhem', 64),
             ('legendary', 124),
             ('drop', 172),
             ('anywhere', 103),
             ('else', 285),
             ('6', 670),
             ('sucks', 290),
             ('alot', 31),
             ('these', 1304),
             ('disappointing', 82),
             ('elsewhere', 13),
             ('disssapointing', 1),
             ('bethesda', 32),
             ('completely', 271),
             ('days', 660),
             ('having', 657),
             ('foot', 38),
             ('unk', 2356),
             ('force', 95),
             ('check', 582),
             ('epic', 360),
             ('streamer', 44),
             ('watch', 995),
             ('striptease', 2),
             ('our', 1368),
             ('big', 781),
             ('blaming', 8),
             ('sight', 22),
             ('tardiness', 2),
             ('little', 502),
             ('bit', 644),
             ('called', 231),
             ('early', 220),
             ('work', 1043),
             ("can't", 1422),
             ('sorry', 295),
             ('loves', 47),
             ('twitch', 1067),
             ('tv', 1335),
             ('punnisenpai', 3),
             ('borderland', 12),
             ('morning', 289),
             ('catch', 52),
             ('love', 2481),
             ('guilty', 34),
             ('sobriety', 1),
             ('borderline', 5),
             ('why', 2395),
             ('does', 610),
             ('every', 1152),
             ('slicked', 4),
             ('hair', 105),
             ('haven’t', 93),
             ('heard', 144),
             ('bangs', 5),
             ('stupid', 461),
             ('assholes', 43),
             ('border', 39),
             ('countries', 22),
             ('your', 3524),
             ('fallen', 27),
             ('off', 1043),
             ('are', 4647),
             ('aliens', 22),
             ('beth', 9),
             ('she', 274),
             ('haven', 42),
             ('’', 2020),
             ('t', 3070),
             ('enough', 381),
             ('gray', 11),
             ('practically', 16),
             ('france', 4),
             ('greedy', 43),
             ('45', 41),
             ('what', 2502),
             ('going', 1538),
             ('finish', 137),
             ('today', 1241),
             ("i've", 1039),
             ('commands', 25),
             ('set', 229),
             ('looking', 605),
             ('forward', 316),
             ('starting', 224),
             ('about', 2799),
             ('hour', 254),
             ('start', 513),
             ('an', 2707),
             ('installed', 75),
             ('events', 86),
             ('look', 782),
             ('20', 686),
             ('cleaning', 9),
             ('just', 5423),
             ('her', 595),
             ('volume', 20),
             ('awesome', 642),
             ('server', 296),
             ('imma', 55),
             ('probably', 480),
             ('play', 3029),
             ('tps', 11),
             ("that'll", 14),
             ('playing', 1864),
             ("it's", 2186),
             ("that'yer", 1),
             ('ll', 88),
             ('video', 1055),
             ('own', 408),
             ('profzeroo', 5),
             ('w', 371),
             ('3‼', 2),
             ('him', 565),
             ('buff', 138),
             ('ly', 627),
             ('2wmmip5', 6),
             ('say', 816),
             ('shouts', 19),
             ('chat', 113),
             ('chance', 437),
             ('shout', 86),
             ('upcoming', 62),
             ('profzero', 1),
             ('p', 336),
             ('–', 190),
             ('also', 1258),
             ('shows', 166),
             ('via', 797),
             ('at', 4178),
             ('officially', 79),
             ('series', 1088),
             ('its', 1456),
             ('movies', 35),
             ('invitation', 8),
             ('invites', 2),
             ('yessssssss', 4),
             ('fick', 5),
             ('yessssss', 2),
             ('hate', 676),
             ('easy', 216),
             ('modifier', 11),
             ('event', 272),
             ('won’t', 112),
             ('forever', 143),
             ('most', 972),
             ('i’ve', 313),
             ('game', 7337),
             ('since', 795),
             ('they', 2924),
             ('added', 113),
             ('them', 1319),
             ('horrible', 91),
             ('modifiers', 22),
             ('please', 1669),
             ('give', 655),
             ('option', 129),
             ('turn', 204),
             ('pls', 171),
             ('simple', 119),
             ('chaos', 40),
             ("won't", 344),
             ("that's", 480),
             ('terrible', 294),
             ('saying', 277),
             ('day', 1318),
             ('9', 331),
             ('ability', 43),
             ('thinking', 187),
             ('total', 109),
             ('won', 488),
             ('absolutely', 393),
             ('ridiculous', 181),
             ('ve', 189),
             ('almost', 477),
             ('do', 2472),
             ('best', 1918),
             ('taken', 108),
             ('past', 217),
             ('until', 501),
             ('send', 100),
             ('grounded', 5),
             ('looked', 110),
             ('pretty', 575),
             ('cool', 565),
             ('despite', 88),
             ('tier', 64),
             ('unfunny', 6),
             ('writing', 68),
             ('became', 78),
             ('yet', 470),
             ('another', 883),
             ('survival', 19),
             ('crafting', 5),
             ('can’t', 465),
             ('shitty', 138),
             ('trend', 37),
             ('die', 262),
             ('crappy', 43),
             ('grosskreutz', 1),
             ('spelling', 12),
             ('turned', 115),
             ('crap', 180),
             ('mod', 18),
             ('deep', 72),
             ('fifth', 16),
             ('format', 23),
             ('ultimately', 7),
             ('mobile', 529),
             ('top', 554),
             ('annoying', 245),
             ('seriously', 254),
             ('submit', 29),
             ('complaint', 29),
             ('ceo', 35),
             ("isn't", 145),
             ('paying', 95),
             ('his', 731),
             ('staff', 77),
             ('bonuses', 20),
             ('file', 79),
             ("doesn't", 446),
             ('pay', 438),
             ('employees', 128),
             ('competitors', 16),
             ('suppose', 23),
             ("isn'ain", 1),
             ('entire', 232),
             ('now', 3489),
             ('any', 988),
             ('offering', 27),
             ('fuckin', 100),
             ('trash', 387),
             ('damn', 893),
             ('rubbish', 19),
             ('fucking', 1661),
             ('thrash', 40),
             ('shit', 2215),
             ('35', 58),
             ('played', 1016),
             ('through', 574),
             ('actual', 127),
             ('great', 1768),
             ('guns', 54),
             ('feel', 565),
             ('once', 270),
             ('felt', 141),
             ('needed', 112),
             ('grind', 70),
             ('story', 476),
             ('other', 718),
             ('hand', 118),
             ('very', 1287),
             ('eventual', 5),
             ('cutscene', 15),
             ('skip', 18),
             ('by', 2336),
             ('weapons', 85),
             ('funny', 215),
             ('sequence', 7),
             ('occasional', 2),
             ('slip', 7),
             ('open', 411),
             ('someone', 581),
             ('side', 162),
             ('endless', 29),
             ('5', 1571),
             ('were', 729),
             ('sure', 446),
             ('oh', 568),
             ("yes'm", 1),
             ('extended', 21),
             ('come', 712),
             ('meet', 92),
             ('lovely', 73),
             ('gaming', 481),
             ('goddesses', 5),
             ('gambling', 23),
             ('beautiful', 395),
             ('gods', 33),
             ('16', 128),
             ('green', 67),
             ('bitch', 169),
             ('slut', 10),
             ('miracle', 27),
             ('ok', 266),
             ('loving', 146),
             ('bombs', 18),
             ('over', 1396),
             ('baghdad', 4),
             ('anything', 424),
             ('gets', 367),
             ('hype', 85),
             ('concept', 59),
             ('a1', 9),
             ('gives', 120),
             ('baghad', 1),
             ('seeing', 225),
             ('take', 667),
             ('sir', 64),
             ('case', 117),
             ('earth', 51),
             ('rpg', 40),
             ('uninstalled', 42),
             ('games', 1946),
             ('space', 85),
             ('uninstall', 17),
             ('room', 118),
             ('deleted', 114),
             ('watching', 335),
             ('already', 749),
             ('bleeding', 17),
             ('edge', 133),
             ('clever', 15),
             ('cross', 96),
             ('between', 185),
             ('overwatch', 891),
             ('domination', 9),
             ('mode', 398),
             ('as', 3098),
             ('crossroads', 1),
             ('future', 157),
             ('2016', 95),
             ('fantasy', 111),
             ('non', 78),
             ('bioshock', 25),
             ('switch', 230),
             ('count', 53),
             ('desert', 13),
             ('montana', 1),
             ('after', 1521),
             ('platinum', 48),
             ('loot', 112),
             ('booty', 15),
             ('lot', 567),
             ('has', 2574),
             ('named', 39),
             ('reason', 345),
             ('laptop', 100),
             ('run', 355),
             ('war', 655),
             ('thunder', 23),
             ('warframe', 5),
             ('high', 310),
             ('settings', 75),
             ('moment', 179),
             ('launch', 321),
             ('csgo', 765),
             ('computer', 151),
             ('crashes', 130),
             ('whole', 451),
             ('breaks', 32),
             ('down', 933),
             ('firefox', 36),
             ('plus', 162),
             ('no', 2801),
             ('easily', 72),
             ('currently', 171),
             ('dare', 23),
             ('mind', 192),
             ('software', 127),
             ('mount', 49),
             ('act', 72),
             ('king', 100),
             ('speeds', 50),
             ('jumping', 51),
             ('more', 2550),
             ('dlcs', 13),
             ('vibing', 3),
             ('playlists', 15),
             ('vibe', 28),
             ('dropping', 73),
             ('quality', 145),
             ('720p', 4),
             ('makes', 521),
             ('difference', 57),
             ('well', 972),
             ('runs', 105),
             ('dumb', 131),
             ('internet', 433),
             ('lmao', 222),
             ('heyitscece', 3),
             ('streaming', 271),
             ('vibrating', 1),
             ('lowering', 5),
             ('jon', 20),
             ('downloading', 49),
             ('tumb', 2),
             ('enter', 99),
             ('gunner', 12),
             ('seat', 20),
             ('fear', 68),
             ('step', 68),
             ('trench', 1),
             ('then', 1160),
             ('wav1bacr5j', 4),
             ('wikipedia', 216),
             ('org', 382),
             ('v', 1007),
             ('omg', 219),
             ('ever', 1230),
             ('thwarted', 4),
             ('bank', 78),
             ('foiled', 1),
             ('threatened', 14),
             ('who', 1540),
             ('late', 182),
             ('trip', 43),
             ('seems', 315),
             ('broken', 376),
             ('with', 7190),
             ('m10', 6),
             ('rates', 18),
             ('constantly', 83),
             ('less', 236),
             ('than', 1331),
             ('lower', 87),
             ('levels', 43),
             ('possible', 138),
             ('2500', 9),
             ('swear', 96),
             ('greens', 5),
             ('blues', 23),
             ('boss', 75),
             ('falling', 53),
             ('when', 2617),
             ('rate', 83),
             ('production', 57),
             ('kinda', 225),
             ('pushing', 37),
             ('normal', 85),
             ('people', 1971),
             ('moving', 75),
             ('recovery', 41),
             ('fast', 173),
             ('next', 851),
             ('gold', 251),
             ('amounts', 12),
             ('worked', 158),
             ('polycule', 4),
             ('tonight', 384),
             ('magical', 23),
             ('evening', 61),
             ('end', 413),
             ('sigh', 27),
             ('allowed', 45),
             ('polyphony', 1),
             ('polyslice', 1),
             ('better', 758),
             ('part', 410),
             ('same', 609),
             ('jackson', 50),
             ('happy', 909),
             ('profit', 40),
             ('wise', 27),
             ('expected', 68),
             ('due', 324),
             ('budget', 32),
             ('realize', 74),
             ('because', 1753),
             ('busted', 29),
             ('again', 1352),
             ('only', 1567),
             ('marketing', 87),
             ('business', 396),
             ('prior', 3),
             ('problem', 507),
             ('far', 422),
             ('always', 807),
             ('fav', 49),
             ('certainly', 97),
             ('guardian', 24),
             ('around', 444),
             ('weekend', 260),
             ('managed', 75),
             ('done', 621),
             ('enjoying', 136),
             ('loved', 216),
             ('slutty', 5),
             ('mechanic', 29),
             ('slutsky', 1),
             ('old', 579),
             ('night', 532),
             ('heeps', 4),
             ("we're", 190),
             ('closer', 31),
             ('towards', 102),
             ('raided', 16),

In [56]:
tokenizer.document_count

57485

In [57]:
len(tokenizer.word_index)

29229

In [58]:
sequence=tokenizer.texts_to_sequences(df["comment"])
sequence

[[309, 170, 13, 120, 5, 3, 55, 1715, 15, 28],
 [3, 112, 396, 4, 2, 6286, 5, 3, 55, 452, 15, 28],
 [309, 170, 13, 120, 5, 3, 55, 452, 15, 28],
 [309, 396, 13, 120, 5, 3, 55, 1715, 15, 28],
 [309, 170, 13, 120, 32, 5, 3, 55, 1715, 15, 22, 28],
 [309, 170, 191, 120, 5, 3, 47, 1715, 15, 28],
 [20,
  3,
  790,
  6,
  357,
  343,
  319,
  238,
  10,
  131,
  48,
  15,
  128,
  123,
  3,
  112,
  6,
  490,
  120,
  621,
  5,
  3922,
  8,
  46,
  7,
  14,
  324,
  737,
  20,
  3,
  726,
  4,
  121,
  485,
  6,
  5320,
  10,
  14,
  279,
  144,
  8,
  2,
  752,
  2050,
  5569,
  2,
  8855,
  3,
  213,
  422,
  38,
  39,
  17,
  15635],
 [20,
  3,
  790,
  6,
  1003,
  7,
  343,
  303,
  238,
  10,
  131,
  48,
  15,
  128,
  123,
  16,
  60,
  6,
  490,
  120,
  621,
  5,
  3922,
  8,
  46,
  7,
  14,
  324,
  737,
  3,
  726,
  4,
  121,
  6,
  5320,
  10,
  14,
  279,
  1179,
  2,
  752,
  1462,
  1813,
  4,
  2,
  8855,
  3,
  213,
  25,
  131,
  38,
  39,
  17,
  15635],
 [20,
  3,
  790,
  6,
  357,
  343,
  303,
  238,
  10,
  131,
  48,
  15,
  128,
  123,
  60,
  6,
  490,
  120,
  621,
  5,
  3922,
  8,
  46,
  7,
  14,
  324,
  737],
 [20,
  3,
  790,
  6,
  357,
  343,
  319,
  238,
  10,
  131,
  48,
  15,
  128,
  123,
  3,
  112,
  6,
  490,
  96,
  621,
  5,
  3922,
  8,
  46,
  7,
  14,
  324,
  737,
  20,
  3,
  726,
  4,
  121,
  485,
  6,
  5320,
  10,
  14,
  279,
  144,
  8,
  2,
  752,
  2050,
  5569,
  2,
  8855,
  3,
  213,
  422,
  38,
  39,
  17,
  15635],
 [1886,
  20,
  3,
  790,
  6,
  357,
  343,
  319,
  238,
  10,
  131,
  48,
  15,
  128,
  123,
  3,
  112,
  6,
  490,
  96,
  621,
  5,
  3922,
  8,
  46,
  7,
  14,
  324,
  737,
  20,
  3,
  726,
  4,
  121,
  485,
  6,
  5320,
  10,
  14,
  279,
  144,
  8,
  2,
  752,
  2050,
  5569,
  2,
  8855,
  3,
  213,
  422,
  38,
  39,
  17,
  15635],
 [29],
 [1691, 354, 1653, 15636, 2937, 909, 1692, 7255, 120, 64, 90, 520, 11, 8856],
 [1691, 354, 1653, 15636, 2937, 909, 1692, 7255, 120, 64, 90, 520, 11, 8856],
 [1691, 354, 1653, 15636, 2937, 909, 1692, 7255, 120, 64, 90, 8230, 11, 8856],
 [1691,
  354,
  1653,
  5854,
  2937,
  24,
  909,
  1692,
  7255,
  120,
  88,
  90,
  520,
  11,
  8856],
 [215,
  1691,
  354,
  545,
  1653,
  1653,
  15636,
  2937,
  2,
  909,
  215,
  1692,
  3,
  7255,
  120,
  64,
  3472,
  90,
  520,
  34,
  11,
  423,
  8856],
 [3, 354, 31, 22, 2937, 4046, 1266, 1692, 2345, 120, 64, 90, 520, 11, 8856],
 [16,
  29,
  2,
  140,
  120,
  1620,
  9,
  6,
  288,
  70,
  272,
  3,
  201,
  103,
  6,
  54,
  2252,
  1920,
  516,
  3,
  87,
  73,
  54,
  50,
  713],
 [12,
  29,
  2,
  140,
  120,
  1620,
  9,
  6,
  288,
  70,
  272,
  3,
  201,
  103,
  6,
  54,
  2252,
  1921,
  516,
  3,
  87,
  73,
  54,
  50,
  713],
 [16,
  29,
  2,
  140,
  120,
  1620,
  9,
  6,
  288,
  70,
  272,
  3,
  201,
  869,
  6,
  54,
  2252,
  1920,
  516,
  3,
  87,
  73,
  1056,
  50,
  713],
 [16,
  3,
  29,
  2,
  140,
  313,
  120,
  1620,
  9,
  6,
  250,
  288,
  153,
  70,
  272,
  3,
  201,
  103,
  6,
  54,
  2252,
  1920,
  516,
  5,
  3,
  87,
  73,
  54,
  50,
  713],
 [16,
  29,
  2,
  140,
  120,
  1620,
  9,
  6,
  721,
  975,
  272,
  3,
  201,
  103,
  6,
  54,
  143,
  1920,
  516,
  3,
  200,
  73,
  54,
  50,
  713],
 [2, 791, 15637, 9, 14, 285, 547, 33, 6, 161, 500, 98, 120, 64],
 [2, 791, 1830, 7, 14, 285, 547, 6, 161, 500],
 [2, 791, 15637, 9, 14, 285, 396, 33, 6, 161, 500, 98, 120, 64],
 [10,
  2,
  791,
  4631,
  15637,
  9,
  14,
  285,
  547,
  1831,
  33,
  6,
  161,
  70,
  500,
  98,
  120,
  64],
 [2, 791, 15637, 9, 14, 285, 547, 102, 179, 161, 500, 98, 120, 179],
 [42,
  512,
  120,
  64,
  222,
  6735,
  156,
  15,
  10,
  1831,
  33,
  218,
  11,
  29,
  131,
  3,
  55,
  337,
  4,
  269,
  503,
  24,
  48,
  27,
  3,
  497,
  20,
  73,
  2390,
  1974,
  259,
  15638,
  42,
  2565,
  89,
  156,
  15,
  20,
  108,
  10,
  2,
  3210,
  8857,
  8858,
  15639,
  5,
  18810],
 [42,
  222,
  222,
  372,
  120,
  64,
  549,
  156,
  15,
  28,
  10,
  1831,
  33,
  11,
  29,
  131,
  491,
  337,
  4,
  269,
  503,
  24,
  48,
  27,
  395,
  73,
  2390,
  1974,
  2009,
  89,
  176,
  10,
  2,
  3210,
  8857,
  8858,
  15639,
  5,
  18810],
 [156,
  15,
  10,
  1831,
  58,
  218,
  11,
  29,
  131,
  491,
  337,
  4,
  37,
  6,
  7723,
  503,
  24,
  48,
  11,
  1477,
  10,
  22,
  73,
  2390,
  1974,
  127,
  77,
  21,
  9,
  18811,
  2009,
  89,
  156,
  15,
  20,
  108,
  10,
  2,
  8857,
  8858,
  22909,
  5,
  22910,
  3210],
 [42,
  512,
  120,
  64,
  228,
  6735,
  156,
  15,
  10,
  1831,
  33,
  188,
  11,
  29,
  131,
  3,
  55,
  337,
  4,
  269,
  5,
  91,
  48,
  27,
  3,
  497,
  20,
  73,
  2390,
  1974,
  259,
  15638,
  42,
  2565,
  97,
  156,
  15,
  20,
  108,
  10,
  2,
  3210,
  8857,
  8858,
  15639,
  5,
  361],
 [42,
  512,
  120,
  64,
  5,
  222,
  6735,
  156,
  15,
  218,
  10,
  1831,
  33,
  218,
  11,
  29,
  131,
  3,
  55,
  337,
  4,
  121,
  269,
  503,
  24,
  48,
  27,
  3,
  497,
  121,
  20,
  73,
  2390,
  1974,
  259,
  15638,
  163,
  42,
  155,
  2565,
  89,
  156,
  15,
  305,
  20,
  108,
  10,
  2,
  3210,
  8857,
  8858,
  65,
  15639,
  5,
  135,
  18810],
 [42,
  512,
  120,
  64,
  222,
  6735,
  306,
  15,
  10,
  1831,
  33,
  20,
  11,
  29,
  131,
  3,
  55,
  337,
  16,
  269,
  503,
  5,
  48,
  27,
  3,
  497,
  302,
  73,
  2390,
  1974,
  34,
  15638,
  42,
  2565,
  89,
  156,
  15,
  20,
  108,
  67,
  235,
  3210,
  8857,
  8858,
  200,
  5,
  114],
 [205,
  3138,
  54,
  518,
  4,
  117,
  12,
  18812,
  1332,
  9,
  2,
  49,
  120,
  64,
  881,
  384,
  21,
  1004,
  4,
  3680,
  5072,
  13,
  1792,
  163,
  4,
  37,
  88,
  1049,
  814,
  259,
  1228,
  530,
  3,
  37,
  256,
  163,
  1332,
  54,
  523,
  3070],
 [205,
  3138,
  54,
  518,
  4,
  117,
  134,
  1478,
  1332,
  9,
  2,
  49,
  120,
  64,
  881,
  10,
  3680,
  5072,
  13,
  1792,
  163,
  4,
  37,
  6,
  1049,
  814,
  259,
  3,
  37,
  256,
  163,
  1332,
  5570],
 [205,
  3138,
  54,
  518,
  4,
  117,
  12,
  22911,
  1332,
  9,
  2,
  49,
  120,
  64,
  881,
  384,
  21,
  1004,
  4,
  3680,
  5072,
  13,
  1792,
  163,
  4,
  37,
  88,
  1049,
  814,
  259,
  5570,
  3,
  37,
  256,
  163,
  1332,
  54,
  523,
  3070],
 [205,
  3001,
  54,
  518,
  4,
  117,
  12,
  18812,
  1332,
  5,
  2,
  49,
  120,
  64,
  11,
  384,
  21,
  1004,
  4,
  3680,
  5072,
  13,
  1792,
  163,
  4,
  37,
  88,
  1049,
  814,
  259,
  1228,
  530,
  3,
  37,
  256,
  163,
  1332,
  54,
  523],
 [205,
  3138,
  54,
  518,
  4,
  117,
  12,
  18812,
  1332,
  9,
  2,
  550,
  49,
  120,
  64,
  260,
  881,
  3,
  384,
  423,
  21,
  1004,
  261,
  4,
  21,
  3680,
  5072,
  13,
  1792,
  163,
  4,
  423,
  37,
  88,
  1049,
  2665,
  814,
  259,
  1228,
  530,
  3,
  37,
  256,
  163,
  1332,
  11,
  54,
  523,
  4,
  3070],
 [68,
  3138,
  54,
  70,
  4,
  117,
  12,
  163,
  1332,
  9,
  2,
  49,
  120,
  64,
  881,
  65,
  21,
  1004,
  4,
  1314,
  5072,
  13,
  1792,
  163,
  4,
  37,
  6,
  1049,
  814,
  259,
  218,
  530,
  3,
  37,
  256,
  163,
  1332,
  54,
  518,
  3070],
 [291, 33, 12, 439, 2391],
 [291, 33, 12, 439, 2391],
 [182, 12, 439, 20698],
 [291, 33, 125, 439, 2391],
 [291, 33, 12, 227, 439, 2391],
 [291, 68, 12, 439, 2391],
 [7724,
  3923,
  10,
  20699,
  6,
  330,
  270,
  7,
  120,
  3,
  87,
  614,
  9,
  646,
  10,
  172,
  503,
  20,
  3,
  119,
  121,
  58,
  70,
  515,
  14,
  2283,
  165,
  129,
  18813],
 [6,
  270,
  7,
  5855,
  3,
  29,
  614,
  4,
  172,
  503,
  527,
  20,
  3,
  119,
  2128,
  58,
  515,
  14,
  62,
  165,
  129,
  18813],
 [2892,
  7,
  22912,
  6,
  270,
  7,
  6,
  11939,
  3,
  29,
  614,
  4,
  172,
  646,
  503,
  20,
  3,
  119,
  2128,
  58],
 [10,
  7724,
  3923,
  10,
  20699,
  6,
  330,
  270,
  7,
  120,
  3,
  87,
  614,
  9,
  646,
  10,
  172,
  503,
  20,
  3,
  119,
  121,
  58,
  70,
  515,
  14,
  2283,
  165,
  129,
  18813],
 [28],
 [66,
  283,
  31,
  151,
  205,
  9,
  120,
  25,
  15640,
  102,
  1208,
  1343,
  15,
  925,
  7,
  11940,
  15,
  362,
  2433],
 [66, 31, 151, 205, 9, 2606, 3924, 25, 15, 27, 925, 7, 11940, 15, 362, 2433],
 [66,
  31,
  218,
  530,
  9,
  2,
  2606,
  3924,
  25,
  35,
  1208,
  3383,
  173,
  25,
  15,
  27,
  925,
  16,
  15,
  26,
  362,
  3925],
 [66,
  283,
  31,
  68,
  205,
  9,
  120,
  25,
  15640,
  102,
  1208,
  65,
  15,
  925,
  7,
  11940,
  15,
  362,
  2433],
 [66,
  7256,
  283,
  31,
  151,
  205,
  9,
  120,
  25,
  546,
  15640,
  16,
  102,
  1208,
  2479,
  78,
  41,
  15,
  925,
  420,
  7,
  6287,
  11940,
  15,
  362,
  2433],
 [66,
  283,
  4840,
  151,
  205,
  9,
  15641,
  25,
  15640,
  102,
  1208,
  1343,
  15,
  925,
  7,
  11940,
  2,
  2434,
  2433],
 [],
 [],
 [2525],
 [61],
 [110,
  4,
  967,
  58,
  120,
  32,
  142,
  174,
  87,
  73,
  49,
  3576,
  617,
  58,
  5,
  112,
  286,
  480,
  4,
  6,
  50,
  269,
  633,
  9,
  52,
  112,
  572],
 [3,
  55,
  967,
  120,
  32,
  142,
  3,
  25,
  73,
  49,
  3576,
  617,
  58,
  5,
  112,
  286,
  480,
  4,
  6,
  50,
  269,
  325,
  9,
  52,
  53,
  572],
 [60,
  110,
  4,
  967,
  120,
  32,
  142,
  3,
  25,
  73,
  49,
  3576,
  1581,
  5,
  60,
  286,
  480,
  4,
  6,
  50,
  269],
 [110,
  4,
  967,
  58,
  120,
  32,
  142,
  174,
  87,
  73,
  49,
  1419,
  617,
  58,
  5,
  112,
  226,
  480,
  4,
  6,
  50,
  269,
  633,
  9,
  52,
  254,
  572],
 [110,
  4,
  967,
  967,
  7257,
  58,
  120,
  32,
  142,
  174,
  23,
  87,
  287,
  73,
  49,
  3576,
  617,
  28,
  58,
  5,
  112,
  286,
  480,
  11,
  4,
  6,
  50,
  269,
  633,
  9,
  52,
  112,
  572],
 [110,
  4,
  967,
  58,
  4181,
  32,
  142,
  174,
  87,
  73,
  271,
  513,
  617,
  58,
  5,
  8,
  286,
  480,
  4,
  6,
  50,
  269,
  633,
  9,
  52,
  112,
  572],
 [2029, 346, 43, 73, 120, 6288, 9, 6, 270, 5321, 21, 131],
 [2029, 8, 346, 86, 6, 270, 7, 5855, 6288, 16, 55, 21, 131],
 [2029, 55, 346, 43, 73, 2606, 6288, 9, 6, 270, 74, 110, 4, 21, 131],
 [2029, 346, 43, 215, 120, 6288, 9, 6, 270, 5321, 21, 131],
 [10, 2029, 346, 43, 73, 120, 6288, 9, 6, 270, 22913, 1392, 21, 6, 131],
 [2029, 346, 87, 73, 168, 6288, 9, 6, 270, 5321, 121, 131],
 [46,
  7,
  125,
  389,
  11941,
  8,
  215,
  425,
  120,
  20700,
  2128,
  299,
  144,
  959,
  278,
  8859,
  219,
  2391,
  4311,
  9,
  1128,
  10,
  6,
  374,
  4,
  21,
  9,
  6,
  396,
  2391,
  4311,
  1420,
  33],
 [46,
  7,
  125,
  389,
  11941,
  8,
  215,
  425,
  120,
  64,
  2128,
  299,
  144,
  959,
  278,
  8859,
  219,
  2391,
  4311,
  9,
  1128,
  10,
  6,
  374,
  4,
  21,
  9,
  53,
  1832,
  46,
  2391,
  4311,
  1420,
  33],
 [46,
  7,
  125,
  389,
  22914,
  215,
  425,
  120,
  64,
  2128,
  299,
  144,
  959,
  278,
  8859,
  219,
  269,
  4311,
  9,
  1128,
  10,
  6,
  1128,
  10,
  6,
  374,
  4,
  21,
  9,
  6,
  396,
  269,
  4311,
  1420,
  33],
 [46,
  7,
  125,
  389,
  11941,
  8,
  215,
  120,
  20700,
  2128,
  299,
  144,
  959,
  278,
  8859,
  464,
  219,
  73,
  4311,
  9,
  1128,
  748,
  6,
  374,
  4,
  21,
  9,
  6,
  396,
  141,
  1420,
  33],
 [46,
  7,
  125,
  839,
  389,
  11941,
  8,
  215,
  223,
  425,
  30,
  120,
  64,
  5,
  68,
  2128,
  299,
  144,
  2,
  959,
  278,
  4,
  8859,
  4,
  219,
  2391,
  4311,
  9,
  1128,
  10,
  6,
  374,
  4,
  1515,
  21,
  9,
  6,
  162,
  396,
  2391,
  4311,
  88,
  1420,
  33],
 [46,
  7,
  116,
  389,
  2837,
  8,
  215,
  425,
  11941,
  64,
  2128,
  299,
  34,
  959,
  278,
  8859,
  10,
  2391,
  4311,
  9,
  7725,
  65,
  6,
  374,
  4,
  21,
  33,
  6,
  396,
  28,
  64,
  20701],
 [98, 15642],
 [11942, 20702],
 [98, 15642],
 [98, 15642, 68],
 [6, 98, 15642],
 [98, 15],
 [3,
  255,
  16,
  12,
  656,
  1792,
  6289,
  548,
  13,
  1792,
  1140,
  179,
  933,
  12,
  8,
  2,
  185,
  131,
  486,
  103,
  9,
  2,
  18,
  224,
  44,
  1129,
  132,
  1367,
  3926,
  120,
  99,
  263,
  22,
  2,
  1023,
  4,
  43,
  1792,
  163,
  24,
  698,
  2,
  3926,
  173,
  818],
 [3,
  255,
  16,
  12,
  1075,
  2566,
  6289,
  548,
  13,
  2566,
  456,
  179,
  933,
  347,
  2,
  185,
  131,
  174,
  103,
  9,
  2,
  18,
  224,
  44,
  1129,
  517,
  3926,
  120,
  99,
  263,
  22,
  2,
  1023,
  4,
  43,
  2566,
  163,
  24,
  698,
  173,
  2,
  3926],
 [3,
  255,
  16,
  12,
  656,
  1792,
  6289,
  548,
  13,
  1792,
  456,
  179,
  933,
  12,
  8,
  2,
  185,
  131,
  174,
  103,
  9,
  2,
  18,
  224,
  44,
  1129,
  132,
  1367,
  3926,
  120,
  99,
  263,
  22,
  2,
  1023,
  4,
  43,
  1792,
  163,
  24,
  698,
  2,
  3926,
  173,
  818],
 [3,
  255,
  541,
  12,
  656,
  133,
  469,
  548,
  13,
  1792,
  1140,
  179,
  933,
  12,
  8,
  2,
  185,
  131,
  486,
  103,
  9,
  2,
  18,
  224,
  44,
  1129,
  132,
  1367,
  3926,
  120,
  99,
  263,
  22,
  73,
  2435,
  4,
  43,
  1792,
  163,
  24,
  698,
  2,
  3926,
  173,
  818],
 [3,
  255,
  758,
  16,
  12,
  656,
  1792,
  6289,
  548,
  13,
  1168,
  1792,
  340,
  78,
  41,
  179,
  933,
  12,
  8,
  2,
  407,
  185,
  783,
  131,
  516,
  3,
  78,
  750,
  103,
  9,
  2,
  18,
  352,
  224,
  44,
  1129,
  132,
  1367,
  3926,
  120,
  99,
  63,
  263,
  22,
  2,
  1023,
  1023,
  4,
  6,
  43,
  1792,
  163,
  24,
  698,
  2,
  3926,
  173,
  818],
 [3,
  255,
  16,
  12,
  656,
  1367,
  6289,
  548,
  13,
  18,
  163,
  179,
  933,
  16,
  8,
  2,
  83,
  131,
  486,
  1180,
  9,
  2,
  652,
  331,
  44,
  1129,
  132,
  1367,
  3926,
  120,
  99,
  1253,
  22,
  2,
  1023,
  4,
  43,
  1792,
  163,
  24,
  698,
  2,
  3926,
  10,
  818],
 [11943,
  352,
  1157,
  294,
  300,
  91,
  1393,
  2,
  120,
  1793,
  8860,
  1716,
  331,
  11,
  1528,
  356,
  206,
  4312,
  11944,
  18,
  3,
  54,
  360,
  153,
  10,
  12,
  960,
  2719,
  4,
  563],
 [11943,
  1157,
  300,
  1393,
  2,
  11939,
  8860,
  1716,
  331,
  11,
  1528,
  206,
  4312,
  11944,
  18,
  3,
  54,
  119,
  153,
  10,
  12,
  2436,
  2719,
  4,
  563],
 [22915,
  1157,
  294,
  300,
  91,
  1393,
  2,
  8860,
  5856,
  331,
  11,
  1113,
  191,
  206,
  4312,
  18,
  3,
  54,
  119,
  153,
  10,
  12,
  786,
  2719,
  4,
  563],
 [11943,
  352,
  1157,
  294,
  300,
  144,
  1393,
  2,
  120,
  1793,
  8860,
  1716,
  331,
  11,
  1528,
  356,
  53,
  4312,
  11944,
  18,
  3,
  54,
  360,
  153,
  10,
  12,
  960,
  4450,
  4,
  563],
 [1637,
  11943,
  352,
  1157,
  294,
  300,
  91,
  1393,
  2,
  120,
  4841,
  1793,
  8860,
  1716,
  3777,
  331,
  8231,
  11,
  1528,
  356,
  206,
  4312,
  11944,
  318,
  18,
  3,
  54,
  47,
  78,
  41,
  153,
  10,
  12,
  960,
  2719,
  633,
  4,
  563],
 [11943,
  352,
  29,
  294,
  300,
  91,
  1393,
  2,
  307,
  1793,
  8860,
  1716,
  331,
  42,
  1528,
  356,
  206,
  591,
  11944,
  18,
  3,
  573,
  360,
  153,
  13,
  12,
  960,
  2719,
  4,
  563],
 [120, 67, 63, 3, 3211, 6, 3212, 35, 2838, 921, 1315, 243, 1554, 114, 4182],
 [120, 67, 47, 3, 1516, 6, 3212, 35, 2838, 368, 373, 243, 1032, 114, 4182],
 [120, 67, 4, 1516, 6, 3212, 35, 2838, 368, 373, 243, 1032, 4182],
 [120, 67, 200, 3, 3211, 6, 3212, 35, 2838, 921, 1315, 243, 4842, 114, 4182],
 [120,
  67,
  63,
  3778,
  3,
  3211,
  6,
  3212,
  35,
  2838,
  22916,
  41,
  91,
  1315,
  243,
  610,
  1554,
  114,
  4182],
 [36, 67, 63, 3, 3211, 183, 3212, 35, 2838, 921, 3384, 243, 1554, 114, 4182],
 [28, 2, 120, 26, 1254, 410],
 [28, 2, 120, 26, 202, 4313],
 [28, 2, 120, 26, 100, 2567],
 [28, 2, 120, 72, 1254, 410],
 [1947, 28, 2, 120, 26, 1254, 410],
 [28, 2, 120, 26, 1254, 362],
 [222,
  177,
  295,
  120,
  64,
  2,
  1038,
  18,
  43,
  8,
  92,
  352,
  28,
  2051,
  301,
  131,
  5,
  3,
  155,
  552,
  944,
  31,
  3,
  1141,
  4,
  1673,
  16,
  353,
  13,
  2,
  247,
  1083,
  28,
  3,
  55,
  219,
  8,
  16,
  60,
  137,
  108,
  20,
  286,
  480,
  4,
  2,
  11945,
  5073,
  4451],
 [222,
  177,
  69,
  120,
  64,
  2,
  1038,
  18,
  8,
  92,
  352,
  28,
  1431,
  301,
  660,
  5,
  3,
  155,
  944,
  31,
  3,
  103,
  4,
  1673,
  13,
  2,
  247,
  1083,
  28,
  3,
  55,
  219,
  8,
  16,
  3,
  112,
  137,
  108,
  286,
  480,
  4,
  2,
  11945,
  8232,
  4451],
 [12,
  353,
  13,
  2,
  247,
  1083,
  28,
  3,
  55,
  219,
  8,
  16,
  60,
  286,
  480,
  4,
  53,
  20703,
  8233],
 [222,
  177,
  295,
  120,
  64,
  2,
  386,
  18,
  43,
  8,
  92,
  352,
  28,
  2051,
  301,
  131,
  5,
  3,
  155,
  552,
  944,
  31,
  3,
  1141,
  4,
  1673,
  2,
  353,
  13,
  4,
  206,
  1083,
  28,
  3,
  55,
  219,
  8,
  16,
  60,
  137,
  108,
  20,
  286,
  480,
  4,
  116,
  11945,
  5073,
  4451],
 [222,
  177,
  295,
  120,
  64,
  2,
  1038,
  18,
  3,
  43,
  8,
  92,
  352,
  28,
  2051,
  301,
  131,
  5,
  356,
  3,
  155,
  552,
  944,
  108,
  31,
  292,
  3,
  573,
  1141,
  4,
  1673,
  16,
  294,
  353,
  13,
  2,
  247,
  854,
  1083,
  28,
  3,
  55,
  219,
  8,
  16,
  60,
  137,
  202,
  108,
  20,
  480,
  286,
  480,
  4,
  2,
  11945,
  3213,
  5073,
  4451],
 [222,
  177,
  295,
  120,
  106,
  2,
  1038,
  18,
  43,
  8,
  92,
  352,
  28,
  2051,
  244,
  131,
  5,
  3,
  155,
  552,
  944,
  369,
  3,
  1141,
  4,
  1673,
  16,
  353,
  8,
  2,
  247,
  1083,
  24,
  3,
  55,
  219,
  36,
  297,
  22917,
  137,
  108,
  20,
  286,
  480,
  4,
  2,
  4047,
  5073,
  4451],
 [252, 1355, 46, 7, 2, 1621, 344, 11946],
 [1355, 46, 7, 2, 1621, 3779, 11946],
 [252, 1355, 46, 7, 2, 404, 2938, 7, 3779],
 [252, 4, 46, 7, 2, 1621, 344, 11946],
 [1033, 252, 1355, 46, 7, 2, 1621, 344, 11946],
 [252, 1355, 46, 7, 2, 1621, 1733, 11946],
 [61, 6, 825],
 [61, 6, 6736],
 [61, 517, 825],
 [61, 6, 825],
 [61, 6, 3385],
 [558,
  3,
  112,
  918,
  12,
  141,
  86,
  4452,
  122,
  15643,
  9,
  377,
  433,
  22,
  1432,
  137,
  120,
  31,
  5,
  2,
  1922,
  8,
  7258],
 [558,
  60,
  918,
  12,
  141,
  86,
  4452,
  122,
  15643,
  9,
  238,
  1068,
  22,
  6,
  1432,
  137,
  120,
  31,
  5,
  2,
  1922,
  8,
  7258],
 [558,
  3,
  112,
  918,
  12,
  141,
  86,
  4452,
  122,
  22918,
  9,
  377,
  433,
  22,
  144,
  137,
  120,
  31,
  5,
  2,
  1922,
  8,
  7258],
 [558,
  3,
  112,
  918,
  12,
  141,
  628,
  257,
  122,
  15643,
  9,
  377,
  433,
  22,
  1432,
  137,
  120,
  31,
  5,
  2,
  1922,
  8,
  271],
 [558,
  1794,
  3,
  112,
  918,
  12,
  141,
  23,
  86,
  4452,
  122,
  15643,
  5,
  9,
  1093,
  377,
  433,
  116,
  22,
  1432,
  3,
  137,
  120,
  31,
  5,
  2,
  1922,
  8,
  7258],
 [558,
  3,
  112,
  918,
  12,
  141,
  86,
  4452,
  5,
  2156,
  9,
  377,
  433,
  22,
  1432,
  137,
  50,
  2568,
  5,
  2,
  1922,
  8,
  7258],
 [23, 2480, 28, 7, 14, 247, 82, 4, 121, 1433, 10, 120, 64],
 [23, 4632, 28, 14, 247, 82, 4, 121, 1084, 10, 120, 64],
 [23, 1118, 28, 14, 247, 82, 4, 121, 1084, 10, 120, 64],
 [23, 2480, 28, 7, 14, 247, 82, 55, 121, 1433, 10, 120, 64],
 [23, 2480, 28, 247, 7, 14, 14, 247, 82, 4, 121, 1433, 10, 465, 120, 64],
 [23, 2480, 28, 7, 28, 247, 82, 9, 121, 1433, 10, 120, 64],
 [241,
  918,
  4633,
  994,
  61,
  6,
  5074,
  18,
  1300,
  763,
  203,
  120,
  5,
  7259,
  18,
  400,
  300,
  40],
 [3,
  62,
  4633,
  994,
  61,
  6,
  5074,
  18,
  22919,
  7,
  203,
  120,
  5,
  7259,
  18,
  400,
  300,
  40],
 [1300, 763, 203, 120, 5, 7259, 18, 400, 300, 40],
 [241,
  918,
  4633,
  994,
  61,
  6,
  131,
  18,
  1300,
  763,
  203,
  120,
  5,
  90,
  18,
  400,
  300,
  40],
 [241,
  141,
  918,
  2,
  4633,
  994,
  61,
  8,
  6,
  5074,
  18,
  1300,
  763,
  203,
  120,
  5,
  878,
  7259,
  18,
  400,
  1316,
  300,
  33,
  40],
 [241,
  177,
  4633,
  994,
  61,
  6,
  5074,
  18,
  1300,
  763,
  1152,
  120,
  1529,
  7259,
  18,
  400,
  86,
  40],
 [3577, 5, 120, 396, 4, 2, 615, 825, 2097, 22, 2, 98, 9],
 [3577, 5, 120, 396, 4, 2, 615, 825, 2097, 22, 2, 98, 9],
 [3577, 5, 120, 396, 4, 2, 5571, 825, 2097, 22, 2, 98, 9],
 [3577, 22920, 5, 247, 120, 26, 396, 4, 2, 615, 825, 2097, 22, 2, 98, 9],
 [3577, 5, 120, 396, 111, 35, 615, 825, 2097, 22, 2, 98, 9],
 [2253, 8, 2, 83, 1142, 120],

In [59]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'it': 11,
 'this': 12,
 'on': 13,
 'my': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'be': 21,
 'me': 22,
 'just': 23,
 'but': 24,
 'have': 25,
 'are': 26,
 'not': 27,
 'all': 28,
 'was': 29,
 'at': 30,
 'like': 31,
 '2': 32,
 'out': 33,
 'from': 34,
 'your': 35,
 'now': 36,
 'get': 37,
 'pic': 38,
 'twitter': 39,
 'as': 40,
 't': 41,
 'we': 42,
 'play': 43,
 'they': 44,
 'johnson': 45,
 'one': 46,
 'can': 47,
 'if': 48,
 'new': 49,
 'good': 50,
 'no': 51,
 'about': 52,
 'an': 53,
 'really': 54,
 'will': 55,
 'when': 56,
 'has': 57,
 'up': 58,
 'more': 59,
 "i'm": 60,
 'what': 61,
 'love': 62,
 'do': 63,
 '3': 64,
 'or': 65,
 'why': 66,
 'how': 67,
 'unk': 68,
 'by': 69,
 'time': 70,
 'co': 71,
 'shit': 72,
 'some': 73,
 "it's": 74,
 'been': 75,
 'amazon': 76,
 'still': 77,
 '’': 78,
 'https': 79,
 'people': 80,
 'facebook': 81,
 'games': 82,
 'best': 83,
 'microsoft': 84,
 'verizon': 85,
 'playing': 86,
 'got': 87,
 '1': 88,
 'see': 89,
 'xbox': 90,
 'even': 91,
 'great': 92,
 'dead': 93,
 'because': 94,
 'google': 95,
 'rhandlerr': 96,
 'go': 97,
 'fuck': 98,
 'please': 99,
 'fucking': 100,
 'red': 101,
 'back': 102,
 'had': 103,
 'us': 104,
 'home': 105,
 '5': 106,
 'only': 107,
 'much': 108,
 'who': 109,
 'going': 110,
 'after': 111,
 'am': 112,
 'nvidia': 113,
 'their': 114,
 's': 115,
 'its': 116,
 'fix': 117,
 'there': 118,
 "can't": 119,
 'borderlands': 120,
 'make': 121,
 'over': 122,
 'know': 123,
 'fifa': 124,
 'our': 125,
 'again': 126,
 'would': 127,
 "don't": 128,
 'tv': 129,
 'than': 130,
 'fun': 131,
 'them': 132,
 'day': 133,
 'these': 134,
 '4': 135,
 '2020': 136,
 'very': 137,
 'eamaddennfl': 138,
 '…': 139,
 'first': 140,
 'also': 141,
 'today': 142,
 'bad': 143,
 'here': 144,
 'ever': 145,
 'want': 146,
 'nba2k': 147,
 'rainbow6game': 148,
 'then': 149,
 'pubg': 150,
 'every': 151,
 'he': 152,
 'wait': 153,
 'redemption': 154,
 'never': 155,
 'thank': 156,
 'x': 157,
 'ps5': 158,
 'call': 159,
 'world': 160,
 'year': 161,
 'series': 162,
 '10': 163,
 'depot': 164,
 'twitch': 165,
 'news': 166,
 'gta': 167,
 'video': 168,
 'right': 169,
 'getting': 170,
 'too': 171,
 'work': 172,
 'off': 173,
 "i've": 174,
 'think': 175,
 'thanks': 176,
 'played': 177,
 'amazing': 178,
 'last': 179,
 'legends': 180,
 'v': 181,
 'watch': 182,
 'any': 183,
 'league': 184,
 'most': 185,
 'well': 186,
 'help': 187,
 'guys': 188,
 'u': 189,
 'being': 190,
 'into': 191,
 'black': 192,
 'ghostrecon': 193,
 'i’m': 194,
 'down': 195,
 'years': 196,
 'youtu': 197,
 'looks': 198,
 'happy': 199,
 'did': 200,
 'actually': 201,
 'damn': 202,
 'overwatch': 203,
 'warcraft': 204,
 'man': 205,
 'another': 206,
 'youtube': 207,
 'creed': 208,
 'stop': 209,
 'team': 210,
 'next': 211,
 'buy': 212,
 'made': 213,
 'should': 214,
 'live': 215,
 'need': 216,
 'battlefield': 217,
 'everyone': 218,
 'say': 219,
 'duty': 220,
 'always': 221,
 'finally': 222,
 'via': 223,
 'since': 224,
 'could': 225,
 'look': 226,
 'big': 227,
 'update': 228,
 'm': 229,
 'which': 230,
 'hearthstone': 231,
 'players': 232,
 'csgo': 233,
 'way': 234,
 'many': 235,
 'better': 236,
 'free': 237,
 'something': 238,
 'excited': 239,
 'it’s': 240,
 'already': 241,
 'online': 242,
 'his': 243,
 'were': 244,
 'money': 245,
 'win': 246,
 'other': 247,
 'fortnite': 248,
 'store': 249,
 'nice': 250,
 'thing': 251,
 'come': 252,
 'playstation': 253,
 '20': 254,
 'hate': 255,
 '6': 256,
 'take': 257,
 'playapex': 258,
 'while': 259,
 'days': 260,
 'having': 261,
 'support': 262,
 'give': 263,
 'war': 264,
 'two': 265,
 'before': 266,
 'wtf': 267,
 'wow': 268,
 'stream': 269,
 'bit': 270,
 'awesome': 271,
 'where': 272,
 'ass': 273,
 'keep': 274,
 'gonna': 275,
 'trying': 276,
 'servers': 277,
 'ly': 278,
 'pc': 279,
 'lol': 280,
 'done': 281,
 'ubisoft': 282,
 'does': 283,
 'same': 284,
 'life': 285,
 'looking': 286,
 'her': 287,
 'long': 288,
 'baby': 289,
 'everything': 290,
 'check': 291,
 'someone': 292,
 'old': 293,
 'pretty': 294,
 'through': 295,
 'dota': 296,
 'oh': 297,
 'lot': 298,
 'him': 299,
 'cool': 300,
 'feel': 301,
 'use': 302,
 'doing': 303,
 'super': 304,
 'both': 305,
 'hey': 306,
 'top': 307,
 'nothing': 308,
 'im': 309,
 'card': 310,
 'company': 311,
 'hell': 312,
 'real': 313,
 'uk': 314,
 'account': 315,
 'night': 316,
 'things': 317,
 'mobile': 318,
 'making': 319,
 'such': 320,
 'cyberpunk': 321,
 'makes': 322,
 'ops': 323,
 'favorite': 324,
 'start': 325,
 'problem': 326,
 'anyone': 327,
 '2077': 328,
 'working': 329,
 'little': 330,
 'until': 331,
 '7': 332,
 'powder': 333,
 'cold': 334,
 'worst': 335,
 'those': 336,
 'try': 337,
 'literally': 338,
 'phone': 339,
 'won': 340,
 'god': 341,
 'service': 342,
 'hours': 343,
 'gaming': 344,
 '100': 345,
 'probably': 346,
 "that's": 347,
 'ea': 348,
 'let': 349,
 'week': 350,
 'player': 351,
 'almost': 352,
 'story': 353,
 'hard': 354,
 'said': 355,
 'yet': 356,
 'few': 357,
 'season': 358,
 'against': 359,
 'can’t': 360,
 'hope': 361,
 'stupid': 362,
 'times': 363,
 'show': 364,
 'whole': 365,
 'miss': 366,
 'app': 367,
 "doesn't": 368,
 'sure': 369,
 'around': 370,
 'apex': 371,
 'find': 372,
 'pay': 373,
 'chance': 374,
 '19': 375,
 'internet': 376,
 'anything': 377,
 '2k': 378,
 'far': 379,
 'ranked': 380,
 'console': 381,
 'lost': 382,
 'release': 383,
 'cant': 384,
 'end': 385,
 'open': 386,
 '21': 387,
 'part': 388,
 'own': 389,
 'don’t': 390,
 'callofduty': 391,
 'says': 392,
 'friends': 393,
 'stuff': 394,
 'maybe': 395,
 'coming': 396,
 'ban': 397,
 'using': 398,
 'crazy': 399,
 'mode': 400,
 'business': 401,
 'ps4': 402,
 'without': 403,
 'beautiful': 404,
 'full': 405,
 'minutes': 406,
 'absolutely': 407,
 "didn't": 408,
 'guy': 409,
 'trash': 410,
 'thought': 411,
 'order': 412,
 'put': 413,
 'tell': 414,
 'dont': 415,
 'cs': 416,
 'tonight': 417,
 'org': 418,
 'italy': 419,
 'enough': 420,
 "assassin's": 421,
 'enjoy': 422,
 'e': 423,
 'broken': 424,
 'w': 425,
 'tried': 426,
 'month': 427,
 'madden': 428,
 'vaccine': 429,
 'tt': 430,
 '0': 431,
 'gameplay': 432,
 'gets': 433,
 'd': 434,
 'interesting': 435,
 'assassins': 436,
 'used': 437,
 'went': 438,
 'epic': 439,
 'care': 440,
 'covid': 441,
 'screen': 442,
 'wrong': 443,
 'run': 444,
 '30': 445,
 'point': 446,
 'though': 447,
 'bought': 448,
 'change': 449,
 '12': 450,
 'sad': 451,
 'kill': 452,
 'y’all': 453,
 'perfect': 454,
 'reason': 455,
 "won't": 456,
 'hit': 457,
 'banned': 458,
 'soon': 459,
 'feels': 460,
 '15': 461,
 'cod': 462,
 'selling': 463,
 'p': 464,
 'watching': 465,
 'may': 466,
 'worth': 467,
 'cause': 468,
 '9': 469,
 'skin': 470,
 'net': 471,
 'problems': 472,
 'due': 473,
 "y'all": 474,
 'launch': 475,
 'system': 476,
 'data': 477,
 'away': 478,
 'price': 479,
 'forward': 480,
 'seems': 481,
 'bro': 482,
 'grand': 483,
 'post': 484,
 'myself': 485,
 'i’ve': 486,
 'definitely': 487,
 "you're": 488,
 '8': 489,
 'huge': 490,
 "i'll": 491,
 'high': 492,
 'based': 493,
 'able': 494,
 'playhearthstone': 495,
 'dota2': 496,
 'might': 497,
 'content': 498,
 'read': 499,
 'ago': 500,
 'months': 501,
 'exciting': 502,
 'tomorrow': 503,
 'patch': 504,
 'pro': 505,
 'homedepot': 506,
 'comes': 507,
 'instead': 508,
 'idea': 509,
 'buying': 510,
 'talc': 511,
 'finished': 512,
 'server': 513,
 'job': 514,
 'sorry': 515,
 'experience': 516,
 'terrible': 517,
 'needs': 518,
 'graphics': 519,
 'dlvr': 520,
 'power': 521,
 'match': 522,
 'sucks': 523,
 'half': 524,
 'cards': 525,
 'odyssey': 526,
 'morning': 527,
 'place': 528,
 'windows': 529,
 'else': 530,
 'community': 531,
 'ift': 532,
 'myteam': 533,
 'second': 534,
 'latest': 535,
 'during': 536,
 'character': 537,
 'pre': 538,
 'started': 539,
 'wanted': 540,
 'saying': 541,
 'share': 542,
 'c': 543,
 'seen': 544,
 'music': 545,
 'she': 546,
 'came': 547,
 'event': 548,
 'yes': 549,
 'completely': 550,
 'streaming': 551,
 'once': 552,
 'wanna': 553,
 'must': 554,
 'found': 555,
 'issues': 556,
 'took': 557,
 'ok': 558,
 'single': 559,
 'rewards': 560,
 '”': 561,
 'name': 562,
 'die': 563,
 'trailer': 564,
 'weekend': 565,
 'anymore': 566,
 'different': 567,
 'mean': 568,
 'honestly': 569,
 'breakpoint': 570,
 'worse': 571,
 'hour': 572,
 'seriously': 573,
 'level': 574,
 'n2k': 575,
 'yo': 576,
 'r': 577,
 'friend': 578,
 'luck': 579,
 'error': 580,
 'gold': 581,
 'hi': 582,
 'running': 583,
 'remember': 584,
 'list': 585,
 'link': 586,
 'guess': 587,
 'rtx': 588,
 'easports': 589,
 'issue': 590,
 'annoying': 591,
 'points': 592,
 'holy': 593,
 'earned': 594,
 'ghost': 595,
 'apple': 596,
 'ready': 597,
 'achievement': 598,
 '•': 599,
 'less': 600,
 'later': 601,
 'either': 602,
 'blizzard': 603,
 'fortnitegame': 604,
 'face': 605,
 'tech': 606,
 'page': 607,
 'yall': 608,
 'deal': 609,
 'entire': 610,
 'customer': 611,
 'products': 612,
 'ubisoftsupport': 613,
 'called': 614,
 'switch': 615,
 'fact': 616,
 'set': 617,
 're': 618,
 'proud': 619,
 'shot': 620,
 'fan': 621,
 'major': 622,
 'three': 623,
 'warzone': 624,
 'kind': 625,
 'left': 626,
 'cannot': 627,
 'seeing': 628,
 'kinda': 629,
 'break': 630,
 'person': 631,
 'talk': 632,
 'starting': 633,
 'saw': 634,
 'understand': 635,
 'least': 636,
 'review': 637,
 'taking': 638,
 'apps': 639,
 'lmao': 640,
 'pass': 641,
 'death': 642,
 'move': 643,
 'j': 644,
 'ronnie2k': 645,
 'early': 646,
 'hear': 647,
 'incredible': 648,
 'bring': 649,
 'omg': 650,
 'india': 651,
 'past': 652,
 'sick': 653,
 'join': 654,
 'house': 655,
 'easy': 656,
 'wikipedia': 657,
 'loved': 658,
 'leagueoflegends': 659,
 'funny': 660,
 'glad': 661,
 'action': 662,
 'waiting': 663,
 'global': 664,
 'small': 665,
 'sounds': 666,
 'companies': 667,
 'follow': 668,
 'fans': 669,
 'killed': 670,
 'b': 671,
 'battle': 672,
 'final': 673,
 'gift': 674,
 'number': 675,
 'class': 676,
 'weeks': 677,
 'tired': 678,
 'each': 679,
 'birthday': 680,
 'believe': 681,
 'gen': 682,
 'quite': 683,
 'mad': 684,
 'happened': 685,
 'delayed': 686,
 '3080': 687,
 'cancer': 688,
 'goes': 689,
 'article': 690,
 'beluba': 691,
 'fantastic': 692,
 'market': 693,
 'family': 694,
 'add': 695,
 'sometimes': 696,
 'franchise': 697,
 'turn': 698,
 "haven't": 699,
 'y': 700,
 'together': 701,
 'line': 702,
 'heart': 703,
 'updates': 704,
 'o': 705,
 'connection': 706,
 'leave': 707,
 'social': 708,
 'n': 709,
 'history': 710,
 'smh': 711,
 'main': 712,
 'kills': 713,
 'modern': 714,
 'totally': 715,
 'code': 716,
 'version': 717,
 "what's": 718,
 'hello': 719,
 'fps': 720,
 'hot': 721,
 'moments': 722,
 'design': 723,
 'bullshit': 724,
 'trump': 725,
 'decided': 726,
 'bc': 727,
 'yeah': 728,
 'close': 729,
 'f': 730,
 'ur': 731,
 'don': 732,
 'yesterday': 733,
 'including': 734,
 'videos': 735,
 'email': 736,
 'characters': 737,
 'mind': 738,
 'movie': 739,
 'speed': 740,
 'gotta': 741,
 'garbage': 742,
 "let's": 743,
 'white': 744,
 'complete': 745,
 'services': 746,
 'suck': 747,
 '–': 748,
 "we're": 749,
 've': 750,
 "there's": 751,
 'original': 752,
 "they're": 753,
 'truly': 754,
 'teams': 755,
 'retweet': 756,
 'canada': 757,
 'thinking': 758,
 'access': 759,
 'edition': 760,
 'spend': 761,
 'released': 762,
 'between': 763,
 'en': 764,
 'available': 765,
 'talking': 766,
 'sound': 767,
 'sony': 768,
 'gone': 769,
 'especially': 770,
 'test': 771,
 'wish': 772,
 'current': 773,
 'beta': 774,
 'keeps': 775,
 '11': 776,
 'that’s': 777,
 'gpu': 778,
 'late': 779,
 'told': 780,
 'sold': 781,
 'nba': 782,
 'ridiculous': 783,
 '“': 784,
 'playoverwatch': 785,
 'crap': 786,
 'daily': 787,
 'million': 788,
 'technology': 789,
 'spent': 790,
 'biggest': 791,
 'moment': 792,
 'absolute': 793,
 'giving': 794,
 'warfare': 795,
 'search': 796,
 'true': 797,
 'instagram': 798,
 'stay': 799,
 'massive': 800,
 'health': 801,
 'within': 802,
 'book': 803,
 'map': 804,
 'under': 805,
 'longer': 806,
 'performance': 807,
 'low': 808,
 'sell': 809,
 'fast': 810,
 'welcome': 811,
 'lose': 812,
 'car': 813,
 'drop': 814,
 'star': 815,
 'item': 816,
 '24': 817,
 'pls': 818,
 'currently': 819,
 'works': 820,
 'controller': 821,
 'customers': 822,
 'nfl': 823,
 'mut': 824,
 'bitch': 825,
 'report': 826,
 'hyped': 827,
 '99': 828,
 'stock': 829,
 'toxic': 830,
 'fire': 831,
 'okay': 832,
 'geforce': 833,
 'greatest': 834,
 'stuck': 835,
 'clips': 836,
 'ordered': 837,
 'unit': 838,
 'shows': 839,
 'feeling': 840,
 'city': 841,
 '50': 842,
 'special': 843,
 'behind': 844,
 'date': 845,
 'means': 846,
 'men': 847,
 'insane': 848,
 'killing': 849,
 'coronavirus': 850,
 'cute': 851,
 'plays': 852,
 'eahelp': 853,
 'side': 854,
 'plus': 855,
 'congratulations': 856,
 'media': 857,
 'activision': 858,
 'prime': 859,
 'tweet': 860,
 'hero': 861,
 'bugs': 862,
 'stopped': 863,
 'campaign': 864,
 'official': 865,
 'digital': 866,
 'ai': 867,
 'valhalla': 868,
 'enjoyed': 869,
 'save': 870,
 'alone': 871,
 'tho': 872,
 'worked': 873,
 'trust': 874,
 'box': 875,
 'iphone': 876,
 'rockstargames': 877,
 'future': 878,
 'wants': 879,
 'trial': 880,
 'dlc': 881,
 'dude': 882,
 'website': 883,
 'happens': 884,
 'bug': 885,
 'girl': 886,
 'changes': 887,
 'received': 888,
 'cyberpunkgame': 889,
 'become': 890,
 'losing': 891,
 'joke': 892,
 'dear': 893,
 'computer': 894,
 'product': 895,
 'seem': 896,
 'imagine': 897,
 'sales': 898,
 'g': 899,
 'control': 900,
 'slow': 901,
 '25': 902,
 'wins': 903,
 'platform': 904,
 'dark': 905,
 'drive': 906,
 'takes': 907,
 'information': 908,
 'powerful': 909,
 'head': 910,
 'download': 911,
 'simply': 912,
 '14': 913,
 'pick': 914,
 'network': 915,
 'rt': 916,
 'racist': 917,
 'loving': 918,
 'safe': 919,
 'somehow': 920,
 "isn't": 921,
 'quality': 922,
 'word': 923,
 'recon': 924,
 'heard': 925,
 'continue': 926,
 'channel': 927,
 'crashing': 928,
 'yourself': 929,
 'boring': 930,
 'fight': 931,
 'broke': 932,
 'forever': 933,
 'log': 934,
 'dog': 935,
 'l': 936,
 'kids': 937,
 'hold': 938,
 'cuz': 939,
 'stores': 940,
 '60': 941,
 'fake': 942,
 'summoners': 943,
 'felt': 944,
 'boy': 945,
 'appreciate': 946,
 'created': 947,
 'disappointed': 948,
 'users': 949,
 '000': 950,
 'gamer': 951,
 'classic': 952,
 'random': 953,
 'articles': 954,
 'siege': 955,
 'important': 956,
 'rest': 957,
 'sense': 958,
 'buff': 959,
 'shitty': 960,
 'possible': 961,
 "i'd": 962,
 'shut': 963,
 'dying': 964,
 'skins': 965,
 'developers': 966,
 'finish': 967,
 'quit': 968,
 'mask': 969,
 'forgot': 970,
 'wild': 971,
 'sale': 972,
 'missing': 973,
 'esports': 974,
 'row': 975,
 'enjoying': 976,
 'art': 977,
 'brand': 978,
 'paid': 979,
 'twice': 980,
 'gave': 981,
 'matter': 982,
 'sea': 983,
 'auto': 984,
 'valve': 985,
 'others': 986,
 'shooting': 987,
 'learn': 988,
 'plan': 989,
 'golden': 990,
 'wonder': 991,
 'lie': 992,
 'amd': 993,
 'edge': 994,
 'group': 995,
 'died': 996,
 'tch': 997,
 'decision': 998,
 'listen': 999,
 'showing': 1000,
 ...}

In [60]:
from keras.utils import pad_sequences

In [61]:
sequences=pad_sequences(sequence,padding="pre")

In [62]:
sequences

array([[   0,    0,    0, ..., 1715,   15,   28],
       [   0,    0,    0, ...,  452,   15,   28],
       [   0,    0,    0, ...,  452,   15,   28],
       ...,
       [   0,    0,    0, ...,  152, 1020, 2536],
       [   0,    0,    0, ...,   78,   41, 2536],
       [   0,    0,    0, ...,    3, 1020, 2536]],
      shape=(57485, 166), dtype=int32)

In [63]:
from sklearn.preprocessing import LabelEncoder

In [64]:
from tensorflow.keras.layers import Dense,SimpleRNN,Input,Embedding
from tensorflow.keras.models import Sequential

In [65]:
label=LabelEncoder()
df["target"]=label.fit_transform(df["target"])
df["target"]

0        2
1        2
2        2
3        2
4        2
        ..
74677    2
74678    2
74679    2
74680    2
74681    2
Name: target, Length: 57485, dtype: int64

In [66]:
X=sequences
y=df["target"].values
y

array([2, 2, 2, ..., 2, 2, 2], shape=(57485,))

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.3)
X_test,X_valid,y_test,y_valid=train_test_split(X_test,y_test,random_state=42,test_size=0.5)

In [69]:
X_train.shape[1]

166

In [70]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(X_train.shape[1],1),return_sequences=False))
model.add(Dense(3,activation="softmax"))

c:\Users\satya\Documents\Desktop\GenAI\Deep Learning\Titanic Model\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [71]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [72]:
model.compile(optimizer="adam",metrics=["accuracy"],loss="sparse_categorical_crossentropy")

In [73]:
model.fit(X_test,y_test,epochs=10,validation_data=(X_valid,y_valid),batch_size=64)

Epoch 1/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 14s 92ms/step - accuracy: 0.3587 - loss: 1.1324 - val_accuracy: 0.3616 - val_loss: 1.0985
Epoch 2/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 10s 76ms/step - accuracy: 0.3633 - loss: 1.0935 - val_accuracy: 0.3585 - val_loss: 1.0983
Epoch 3/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.3698 - loss: 1.0910 - val_accuracy: 0.3608 - val_loss: 1.0951
Epoch 4/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 0.3720 - loss: 1.0910 - val_accuracy: 0.3603 - val_loss: 1.0950
Epoch 5/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.3726 - loss: 1.0899 - val_accuracy: 0.3685 - val_loss: 1.0948
Epoch 6/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.3741 - loss: 1.0890 - val_accuracy: 0.3558 - val_loss: 1.0941
Epoch 7/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.3714 - loss: 1.0886 - val_accuracy: 0.3587 - val_loss: 1.0934
Epoch 8/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.3726 - loss: 1.0910 - val_accuracy: 0.3464 - val_loss: 1.0957
Epoch 9/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.3703 - loss: 1.0898 - val_accuracy: 0.3612 - val_loss: 1.0971
Epoch 10/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.3764 - loss: 1.0900 - val_accuracy: 0.3585 - val_loss: 1.0960

In [82]:
model2=Sequential()
vocab_size=len(tokenizer.word_index)+1
model2.add(Input(shape=(X_train.shape[1],)))
model2.add(Embedding(input_dim=vocab_size,output_dim=64))
model2.add(SimpleRNN(32,return_sequences=True))
model2.add(SimpleRNN(32,return_sequences=False))
model2.add(Dense(3,activation="softmax"))
model2.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 166, 64)        │     1,870,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_12 (SimpleRNN)       │ (None, 166, 32)        │         3,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_13 (SimpleRNN)       │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,876,003 (7.16 MB)

 Trainable params: 1,876,003 (7.16 MB)

 Non-trainable params: 0 (0.00 B)

In [83]:
from tensorflow.keras.callbacks import EarlyStopping
stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [84]:
model2.compile(optimizer="adam",metrics=["accuracy"],loss="sparse_categorical_crossentropy")
model2.fit(X_test,y_test,epochs=100,validation_data=(X_valid,y_valid),batch_size=64,callbacks=[stopping_callback])

Epoch 1/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - accuracy: 0.4787 - loss: 1.0162 - val_accuracy: 0.5960 - val_loss: 0.9079
Epoch 2/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.8320 - loss: 0.4658 - val_accuracy: 0.6705 - val_loss: 0.8122
Epoch 3/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 11s 52ms/step - accuracy: 0.9632 - loss: 0.1298 - val_accuracy: 0.6536 - val_loss: 0.9396
Epoch 4/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9876 - loss: 0.0487 - val_accuracy: 0.6666 - val_loss: 1.0308
Epoch 5/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 54ms/step - accuracy: 0.9929 - loss: 0.0272 - val_accuracy: 0.6682 - val_loss: 1.1113
Epoch 6/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9955 - loss: 0.0184 - val_accuracy: 0.6671 - val_loss: 1.1961
Epoch 7/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9961 - loss: 0.0146 - val_accuracy: 0.6519 - val_loss: 1.2846
Epoch 8/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 52ms/step - accuracy: 0.9965 - loss: 0.0112 - val_accuracy: 0.6510 - val_loss: 1.3517
Epoch 9/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 53ms/step - accuracy: 0.9974 - loss: 0.0086 - val_accuracy: 0.6512 - val_loss: 1.4132
Epoch 10/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9977 - loss: 0.0080 - val_accuracy: 0.6422 - val_loss: 1.4959
Epoch 11/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 37s 277ms/step - accuracy: 0.9976 - loss: 0.0067 - val_accuracy: 0.6439 - val_loss: 1.5358
Epoch 12/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 21s 128ms/step - accuracy: 0.9977 - loss: 0.0060 - val_accuracy: 0.6513 - val_loss: 1.5659

In [85]:
import pickle
with open("tokenizer.pkl","wb") as file:
    pickle.dump(tokenizer,file)

In [86]:
model2.save("Sentimentanalysis.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.